# Generated by Django 4.1rc1 on 2022-08-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_remove_plant_image_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image1',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='plant',
            name='image2',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='plant',
            name='image3',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='plant',
            name='posetr',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
