# Generated by Django 4.1rc1 on 2022-08-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_image1_plant_image2_plant_image3_plant_posetr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='WPlink',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='shortname',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='plant',
            name='title',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='tags',
            field=models.ManyToManyField(to='plants.tags'),
        ),
    ]
